#!/bin/sh
####################################################################################
#
# Description:  Authorizes whether a user is allowed access to a role (TODO)
# Parameters:   1 - The user name
#               2 - The role name
# 
####################################################################################

exit 0
